Allow php 8.1
laminas-api-tools/api-tools-oauth2 pull request #40
Opened 2022-05-11 09:00 UTC by snapshotpl

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Allow install on PHP 8.1

2022-05-11 09:04 UTC, Ocramius commented
Welp, `- Root composer.json requires laminas/laminas-coding-standard ~2.2.0 -> satisfiable by laminas/laminas-coding-standard[2.2.0, 2.2.1].`

Guess `laminas/laminas-coding-standard:~2.3` is needed here.

2022-05-11 09:04 UTC, Ocramius requested changes
Welp, `- Root composer.json requires laminas/laminas-coding-standard ~2.2.0 -> satisfiable by laminas/laminas-coding-standard[2.2.0, 2.2.1].`

Guess `laminas/laminas-coding-standard:~2.3` is needed here.

2022-05-11 09:18 UTC, Ocramius requested changes
```
 1) LaminasTest\ApiTools\OAuth2\Controller\AuthControllerTest::testResource
Laminas\View\Exception\DomainException: Laminas\View\Renderer\PhpRenderer::render: received View Model argument, but template is empty
```

Meanwhile, PHP 7.3 can go away :)

2022-05-11 10:17 UTC, snapshotpl commented
Fix requested https://github.com/bshaffer/oauth2-server-php/pull/1021

2022-05-11 12:15 UTC, Ocramius requested changes
For the CS issues, could we perhaps switch to psr-11, if servicemanager is forced to be at the last version? 🤔

2022-05-13 08:55 UTC, snapshotpl commented
CS issue fixed, so now waiting for https://github.com/bshaffer/oauth2-server-php/pull/1021

2022-05-13 10:04 UTC, Ocramius approved these changes

2022-06-01 09:38 UTC, snapshotpl commented
After squash looks like GA stuck, but before all passed https://github.com/laminas-api-tools/api-tools-oauth2/actions/runs/2420613249 so just waiting for new release oauth2 by @bshaffer

2022-06-01 09:40 UTC, Ocramius requested changes

2022-06-01 09:40 UTC, Ocramius commented on composer.json
> +        "bshaffer/oauth2-server-php": "dev-master#2bfaf9d7bbebe2ba1c1deb48e756ba0b3af4e985 as 1.12",
To be adjusted before merge

2022-06-01 09:40 UTC, Ocramius commented on src/Factory/PdoAdapterFactory.php
> -    public function createService($container)
This is still a BC break :thinking:

2022-06-01 09:40 UTC, Ocramius commented on src/Factory/PdoAdapterFactory.php
> -    public function createService($container)
(applies to other factories as well)

2022-06-02 14:30 UTC, Ocramius requested changes

2022-06-02 14:30 UTC, Ocramius commented on src/Factory/AuthControllerFactory.php
> -    public function createService(ServiceLocatorInterface $controllers, $name = null, $requestedName = null)
@snapshotpl if we keep the BC breaks in, we need a major: can we keep the dead `public` methods for a while, and mark them `@deprecated` instead?

2022-06-02 14:30 UTC, Ocramius commented on src/Factory/AuthControllerFactory.php
> +class AuthControllerFactory
Can we somehow keep `FactoryInterface` to avoid a BC break? :thinking:

2022-06-02 15:47 UTC, bshaffer commented
> CS issue fixed, so now waiting for [bshaffer/oauth2-server-php#1021](https://github.com/bshaffer/oauth2-server-php/pull/1021)

Fixed in https://github.com/bshaffer/oauth2-server-php/releases/tag/v1.12.1

2022-06-02 15:52 UTC, snapshotpl commented
Thanks @bshaffer! All tests are green now!

2022-06-02 16:03 UTC, snapshotpl commented
Not sure why php-cs enforced `interop\container` lowercase :thinking: . But still works

2022-06-03 08:12 UTC, Ocramius commented
> Not sure why php-cs enforced `interop\container` lowercase thinking . But still works

It will break autoloading (depending on autoloading order), so I think we need to either ignore or skip the rule for now :thinking:

2022-06-03 08:59 UTC, Ocramius approved these changes

2022-06-03 08:59 UTC, Ocramius commented on src/Factory/PdoAdapterFactory.php
>  use Interop\Container\ContainerInterface;
These reported CS issues need to be suppressed: I think we may want to run `phpcs -s` to see **which** rule it is, that is raising them.

2022-06-03 09:00 UTC, Ocramius commented on src/Factory/PdoAdapterFactory.php
>  use Interop\Container\ContainerInterface;
Once the build is green due to this, I'm happy to merge+release :)

2022-06-03 09:05 UTC, snapshotpl commented on src/Factory/PdoAdapterFactory.php
>  use Interop\Container\ContainerInterface;
`WebimpressCodingStandard.PHP.CorrectClassNameCase.Invalid` @michalbundyra

2022-06-03 09:08 UTC, Ocramius commented on src/Factory/PdoAdapterFactory.php
>  use Interop\Container\ContainerInterface;
For now, let's just drop it from our local phpcs config (this repo) via exclusion. Should be like https://github.com/Ocramius/ProxyManager/blob/8846623bea8749ded206db3ce701e4e508d516db/phpcs.xml.dist#L20-L21

2022-06-03 09:17 UTC, Ocramius commented
Excellent, also thanks for squashing!

2022-06-03 09:17 UTC, Ocramius approved these changes
Thanks @snapshotpl!

2022-06-03 09:17 UTC, merged